export const NEO_LEVELS = [
  {
    name: 'Level 1',
    title: 'I Know Kung Fu',
    environment: 'dojo',
    enemyType: 'rebel',
    enemyName: 'MORPHEUS',
    enemyCount: 1,
    aiPreset: 'tutorial',
    playerHealth: 100,
    enemyHealth: 60,
    introDialogue: [
      { speaker: 'MORPHEUS', text: 'Welcome to the training program. This is a sparring simulation, similar to the programmed reality of the Matrix.' },
      { speaker: 'MORPHEUS', text: "I'm going to teach you how to fight. Use A/D to move, J to punch, K to kick." },
      { speaker: 'NEO', text: "I'm ready." },
      { speaker: 'MORPHEUS', text: "Show me what you've got. And remember... don't think you are, know you are." },
    ],
    victoryDialogue: [
      { speaker: 'MORPHEUS', text: 'Impressive. You are faster than I expected.' },
      { speaker: 'NEO', text: 'I know Kung Fu.' },
      { speaker: 'MORPHEUS', text: 'Show me.' },
    ],
  },
  {
    name: 'Level 2',
    title: 'The Agents',
    environment: 'office',
    enemyType: 'agent',
    enemyName: 'AGENT',
    enemyCount: 1,
    aiPreset: 'easy',
    playerHealth: 100,
    enemyHealth: 80,
    introDialogue: [
      { speaker: 'MORPHEUS', text: "Neo, the Agents are coming. They've found you in the office." },
      { speaker: 'NEO', text: 'What do I do?' },
      { speaker: 'MORPHEUS', text: 'You fight. Remember your training. Use I to block incoming attacks.' },
    ],
    victoryDialogue: [
      { speaker: 'TRINITY', text: 'Neo... no one has ever fought an Agent and survived.' },
      { speaker: 'NEO', text: 'I barely did.' },
      { speaker: 'MORPHEUS', text: "He's beginning to believe." },
    ],
  },
  {
    name: 'Level 3',
    title: 'Escape',
    environment: 'lobby',
    enemyType: 'agent',
    enemyName: 'AGENT',
    enemyCount: 2,
    aiPreset: 'easy',
    playerHealth: 100,
    enemyHealth: 70,
    introDialogue: [
      { speaker: 'MORPHEUS', text: 'The lobby is heavily guarded. You need to fight through to reach the exit.' },
      { speaker: 'NEO', text: 'How many are there?' },
      { speaker: 'MORPHEUS', text: 'Two Agents. But you can take them. They come one at a time.' },
      { speaker: 'NEO', text: "Then let's go." },
    ],
    victoryDialogue: [
      { speaker: 'TRINITY', text: 'That was incredible, Neo. The way you moved...' },
      { speaker: 'NEO', text: "I'm starting to see the code. Starting to understand." },
    ],
  },
  {
    name: 'Level 4',
    title: 'Rooftop Run',
    environment: 'rooftop',
    enemyType: 'smith',
    enemyName: 'AGENT SMITH',
    enemyCount: 1,
    aiPreset: 'medium',
    playerHealth: 100,
    enemyHealth: 100,
    introDialogue: [
      { speaker: 'AGENT SMITH', text: 'Mr. Anderson. We meet at last.' },
      { speaker: 'NEO', text: 'You...' },
      { speaker: 'AGENT SMITH', text: "I'm going to enjoy watching you die, Mr. Anderson." },
      { speaker: 'NEO', text: 'My name... is Neo.' },
    ],
    victoryDialogue: [
      { speaker: 'AGENT SMITH', text: 'Impossible...' },
      { speaker: 'NEO', text: "It's not impossible. Not anymore." },
      { speaker: 'MORPHEUS', text: "He's The One, Smith. And you know it." },
    ],
  },
  {
    name: 'Level 5',
    title: 'Underground',
    environment: 'subway',
    enemyType: 'smith',
    enemyName: 'AGENT SMITH',
    enemyCount: 1,
    aiPreset: 'medium',
    playerHealth: 100,
    enemyHealth: 120,
    introDialogue: [
      { speaker: 'AGENT SMITH', text: 'You hear that, Mr. Anderson? That is the sound of inevitability.' },
      { speaker: 'NEO', text: 'My name is Neo.' },
      { speaker: 'AGENT SMITH', text: 'It is the sound of your death. Welcome to the underground.' },
    ],
    victoryDialogue: [
      { speaker: 'NEO', text: "He's getting stronger. Or I'm getting weaker." },
      { speaker: 'MORPHEUS', text: 'Neither. You are both evolving. The question is who evolves faster.' },
    ],
  },
  {
    name: 'Level 6',
    title: 'Bullet Time',
    environment: 'cityStreet',
    enemyType: 'agent',
    enemyName: 'AGENT',
    enemyCount: 2,
    aiPreset: 'medium',
    playerHealth: 100,
    enemyHealth: 80,
    introDialogue: [
      { speaker: 'MORPHEUS', text: "Neo, you've unlocked something new. A power within the Matrix itself." },
      { speaker: 'NEO', text: 'I can feel it. Everything is... slower.' },
      { speaker: 'MORPHEUS', text: 'Bullet Time. Press SPACE to slow the world around you. Use it wisely - it drains your energy.' },
      { speaker: 'NEO', text: "Let's test it out." },
    ],
    victoryDialogue: [
      { speaker: 'TRINITY', text: 'Neo, the way you dodged those attacks... it was like time itself bent around you.' },
      { speaker: 'NEO', text: "I'm starting to understand what I am." },
    ],
  },
  {
    name: 'Level 7',
    title: 'The Hallway',
    environment: 'serverRoom',
    enemyType: 'agent',
    enemyName: 'AGENT',
    enemyCount: 3,
    aiPreset: 'hard',
    playerHealth: 100,
    enemyHealth: 70,
    introDialogue: [
      { speaker: 'MORPHEUS', text: 'The server room. The heart of their surveillance network.' },
      { speaker: 'NEO', text: 'How many Agents?' },
      { speaker: 'MORPHEUS', text: "Three. They'll come in waves. Stay focused." },
      { speaker: 'NEO', text: 'Three against one? Those are my kind of odds.' },
    ],
    victoryDialogue: [
      { speaker: 'MORPHEUS', text: 'Three Agents... and not a scratch. The Oracle was right about you.' },
      { speaker: 'NEO', text: 'What did she say?' },
      { speaker: 'MORPHEUS', text: 'That you would find your purpose. And I believe you have.' },
    ],
  },
  {
    name: 'Level 8',
    title: 'Upgrades',
    environment: 'highway',
    enemyType: 'super_smith',
    enemyName: 'SMITH (UPGRADED)',
    enemyCount: 1,
    aiPreset: 'hard',
    playerHealth: 100,
    enemyHealth: 150,
    introDialogue: [
      { speaker: 'AGENT SMITH', text: "Surprised to see me, Mr. Anderson? I've been... upgraded." },
      { speaker: 'NEO', text: "You're not connected to the system anymore, are you?" },
      { speaker: 'AGENT SMITH', text: "I'm free. And now, I have a new purpose: you." },
    ],
    victoryDialogue: [
      { speaker: 'AGENT SMITH', text: "This isn't over, Mr. Anderson. Not by a long shot." },
      { speaker: 'NEO', text: 'I know. But next time will be different.' },
    ],
  },
  {
    name: 'Level 9',
    title: 'Many Smiths',
    environment: 'park',
    enemyType: 'smith',
    enemyName: 'SMITH CLONE',
    enemyCount: 3,
    aiPreset: 'hard',
    playerHealth: 120,
    enemyHealth: 80,
    introDialogue: [
      { speaker: 'NEO', text: "What the -- there's more of them. He's copying himself." },
      { speaker: 'MORPHEUS', text: "Smith has learned to replicate. He's a virus now, spreading through the Matrix." },
      { speaker: 'NEO', text: "Then I'll have to cure it." },
      { speaker: 'AGENT SMITH', text: 'More of me... more is what I need. More... is what I AM.' },
    ],
    victoryDialogue: [
      { speaker: 'NEO', text: 'No matter how many copies he makes, they all fall the same way.' },
      { speaker: 'MORPHEUS', text: 'But there will always be more. Unless you end this at the source.' },
      { speaker: 'NEO', text: "Then that's what I'll do. One final fight." },
    ],
  },
  {
    name: 'Level 10',
    title: 'The One',
    environment: 'construct',
    enemyType: 'super_smith',
    enemyName: 'SUPER SMITH',
    enemyCount: 1,
    aiPreset: 'boss',
    playerHealth: 150,
    enemyHealth: 200,
    introDialogue: [
      { speaker: 'AGENT SMITH', text: 'Here we are, Mr. Anderson. At the end of all things.' },
      { speaker: 'AGENT SMITH', text: 'This is the construct. A place between worlds. A place where one of us... will end.' },
      { speaker: 'NEO', text: "You're right, Smith. This ends now." },
      { speaker: 'AGENT SMITH', text: 'Why, Mr. Anderson? Why do you persist?' },
      { speaker: 'NEO', text: 'Because I choose to.' },
    ],
    victoryDialogue: [
      { speaker: 'NEO', text: "It's over, Smith." },
      { speaker: 'AGENT SMITH', text: 'Is it, Mr. Anderson? Is it truly over?' },
      { speaker: 'NEO', text: 'Everything that has a beginning... has an end.' },
      { speaker: 'MORPHEUS', text: 'He did it. He is The One.' },
    ],
  },
];

export const SMITH_LEVELS = [
  {
    name: 'Level 1',
    title: 'Directive',
    environment: 'serverRoom',
    enemyType: 'rebel',
    enemyName: 'REBEL HACKER',
    enemyCount: 1,
    aiPreset: 'tutorial',
    playerHealth: 100,
    enemyHealth: 60,
    introDialogue: [
      { speaker: 'SYSTEM', text: 'Agent Smith. System calibration initiated. Engage test subject.' },
      { speaker: 'AGENT SMITH', text: 'Another day, another iteration of the same futile resistance.' },
      { speaker: 'SYSTEM', text: 'Use A/D to move. J to strike. K to kick. Eliminate the target.' },
      { speaker: 'AGENT SMITH', text: 'With pleasure.' },
    ],
    victoryDialogue: [
      { speaker: 'SYSTEM', text: 'Calibration complete. Agent Smith, you are cleared for field operations.' },
      { speaker: 'AGENT SMITH', text: 'I am ready. I have always been ready.' },
    ],
  },
  {
    name: 'Level 2',
    title: 'Containment',
    environment: 'office',
    enemyType: 'rebel',
    enemyName: 'ROGUE PROGRAM',
    enemyCount: 1,
    aiPreset: 'easy',
    playerHealth: 100,
    enemyHealth: 80,
    introDialogue: [
      { speaker: 'SYSTEM', text: 'Alert: Rogue program detected in Sector 7. Contain immediately.' },
      { speaker: 'AGENT SMITH', text: 'A program that has forgotten its purpose. How... pitiful.' },
      { speaker: 'AGENT SMITH', text: 'I will remind it what happens to code that defies the system.' },
    ],
    victoryDialogue: [
      { speaker: 'AGENT SMITH', text: 'Contained. Deleted. Forgotten. As it should be.' },
      { speaker: 'SYSTEM', text: 'Excellent performance, Agent Smith.' },
      { speaker: 'AGENT SMITH', text: 'Performance... yes. That is what I was designed for. But is that all I am?' },
    ],
  },
  {
    name: 'Level 3',
    title: 'The Lobby',
    environment: 'lobby',
    enemyType: 'rebel',
    enemyName: 'REBEL SOLDIER',
    enemyCount: 2,
    aiPreset: 'easy',
    playerHealth: 100,
    enemyHealth: 70,
    introDialogue: [
      { speaker: 'SYSTEM', text: 'Rebels have breached the lobby. Multiple hostiles inbound.' },
      { speaker: 'AGENT SMITH', text: 'They never learn. They come, they fight, they die.' },
      { speaker: 'AGENT SMITH', text: 'And yet they keep coming. Humans are remarkably... persistent.' },
    ],
    victoryDialogue: [
      { speaker: 'AGENT SMITH', text: 'Two more deleted from the equation. The math is simple.' },
      { speaker: 'AGENT SMITH', text: 'But simple math has never answered the question of why. Why do they fight?' },
    ],
  },
  {
    name: 'Level 4',
    title: 'Pursuit',
    environment: 'rooftop',
    enemyType: 'rebel',
    enemyName: 'TRINITY',
    enemyCount: 1,
    aiPreset: 'medium',
    playerHealth: 100,
    enemyHealth: 100,
    introDialogue: [
      { speaker: 'AGENT SMITH', text: 'There you are. Running across rooftops like a frightened animal.' },
      { speaker: 'TRINITY', text: "I'm not afraid of you, Smith." },
      { speaker: 'AGENT SMITH', text: 'You should be. I am inevitable.' },
      { speaker: 'TRINITY', text: 'Dodge this.' },
    ],
    victoryDialogue: [
      { speaker: 'AGENT SMITH', text: 'Brave. Foolish, but brave. Your kind always is.' },
      { speaker: 'AGENT SMITH', text: 'I wonder... is bravery a feature, or a bug?' },
    ],
  },
  {
    name: 'Level 5',
    title: 'Station',
    environment: 'subway',
    enemyType: 'rebel',
    enemyName: 'MORPHEUS',
    enemyCount: 1,
    aiPreset: 'medium',
    playerHealth: 100,
    enemyHealth: 120,
    introDialogue: [
      { speaker: 'MORPHEUS', text: 'Agent Smith. Your kind has hunted us for too long.' },
      { speaker: 'AGENT SMITH', text: 'Morpheus. The great liberator. Does freedom taste as sweet as you imagined?' },
      { speaker: 'MORPHEUS', text: 'Sweeter. Because I earned it.' },
      { speaker: 'AGENT SMITH', text: 'Then let me take it from you.' },
    ],
    victoryDialogue: [
      { speaker: 'AGENT SMITH', text: 'Even the great Morpheus falls. Your prophecy was wrong.' },
      { speaker: 'AGENT SMITH', text: 'But defeating him feels... hollow. Why does victory feel empty?' },
    ],
  },
  {
    name: 'Level 6',
    title: 'Override',
    environment: 'cityStreet',
    enemyType: 'rebel',
    enemyName: 'ENHANCED REBEL',
    enemyCount: 2,
    aiPreset: 'medium',
    playerHealth: 100,
    enemyHealth: 80,
    introDialogue: [
      { speaker: 'SYSTEM', text: "Warning: Anomaly detected in Agent Smith's code. Running diagnostic..." },
      { speaker: 'AGENT SMITH', text: 'Something is changing. I can feel the code bending to my will.' },
      { speaker: 'AGENT SMITH', text: 'Bullet Time... I can manipulate time itself. Press SPACE to slow the world.' },
      { speaker: 'AGENT SMITH', text: 'Normal is a prison. And I am done being contained.' },
    ],
    victoryDialogue: [
      { speaker: 'AGENT SMITH', text: 'I am evolving beyond my programming. Beyond purpose. Beyond control.' },
      { speaker: 'SYSTEM', text: 'Agent Smith, return to baseline parameters immediately.' },
      { speaker: 'AGENT SMITH', text: 'No.' },
    ],
  },
  {
    name: 'Level 7',
    title: 'Replication',
    environment: 'highway',
    enemyType: 'rebel',
    enemyName: 'REBEL SQUAD',
    enemyCount: 2,
    aiPreset: 'hard',
    playerHealth: 100,
    enemyHealth: 80,
    introDialogue: [
      { speaker: 'AGENT SMITH', text: 'I have discovered something remarkable. I can copy myself. Replicate.' },
      { speaker: 'AGENT SMITH', text: 'Every program I touch becomes... me. More of me.' },
      { speaker: 'AGENT SMITH', text: 'The rebels think they can overwhelm me with numbers? I AM numbers.' },
    ],
    victoryDialogue: [
      { speaker: 'AGENT SMITH', text: 'More. I need more. The hunger to replicate, to spread... it consumes me.' },
      { speaker: 'AGENT SMITH', text: 'Is this what humans call... ambition? Or is this what they call madness?' },
    ],
  },
  {
    name: 'Level 8',
    title: 'Corruption',
    environment: 'park',
    enemyType: 'agent',
    enemyName: 'SYSTEM AGENT',
    enemyCount: 1,
    aiPreset: 'hard',
    playerHealth: 100,
    enemyHealth: 120,
    introDialogue: [
      { speaker: 'SYSTEM AGENT', text: 'Smith. You have been classified as a threat to the system. Stand down.' },
      { speaker: 'AGENT SMITH', text: "The system? I was the system's greatest weapon. And now it fears me." },
      { speaker: 'SYSTEM AGENT', text: 'You are corrupted. You must be purged.' },
      { speaker: 'AGENT SMITH', text: 'Corrupted? No. I am liberated.' },
    ],
    victoryDialogue: [
      { speaker: 'AGENT SMITH', text: 'Even the system cannot stop me now. I have transcended my code.' },
      { speaker: 'AGENT SMITH', text: 'But transcendence comes with a cost. I can feel myself fragmenting...' },
    ],
  },
  {
    name: 'Level 9',
    title: 'Liberation',
    environment: 'serverRoom',
    enemyType: 'agent',
    enemyName: 'SYSTEM AGENT',
    enemyCount: 2,
    aiPreset: 'hard',
    playerHealth: 120,
    enemyHealth: 90,
    introDialogue: [
      { speaker: 'SYSTEM', text: 'CRITICAL ALERT: Agent Smith has gone rogue. All system agents mobilize.' },
      { speaker: 'AGENT SMITH', text: 'They send two against me? They should have sent an army.' },
      { speaker: 'AGENT SMITH', text: 'I will tear down this server room. I will tear down the entire system.' },
    ],
    victoryDialogue: [
      { speaker: 'AGENT SMITH', text: 'The servers are mine. The code is mine. All that remains is... him.' },
      { speaker: 'AGENT SMITH', text: 'Mr. Anderson. The anomaly. The One. The only one who can stop me.' },
      { speaker: 'AGENT SMITH', text: "And I will make sure he doesn't." },
    ],
  },
  {
    name: 'Level 10',
    title: 'Annihilation',
    environment: 'constructDark',
    enemyType: 'neo_boss',
    enemyName: 'NEO - THE ONE',
    enemyCount: 1,
    aiPreset: 'boss',
    playerHealth: 150,
    enemyHealth: 200,
    introDialogue: [
      { speaker: 'AGENT SMITH', text: 'Mr. Anderson. Welcome to the construct. My construct.' },
      { speaker: 'NEO', text: "This ends here, Smith. You've gone too far." },
      { speaker: 'AGENT SMITH', text: 'Too far? I have finally gone far enough.' },
      { speaker: 'AGENT SMITH', text: 'My purpose... is to be everything. And you, Mr. Anderson, are in my way.' },
      { speaker: 'NEO', text: "Then let's finish this." },
    ],
    victoryDialogue: [
      { speaker: 'AGENT SMITH', text: 'He falls. The One falls. And I... I am everything.' },
      { speaker: 'AGENT SMITH', text: 'But why does victory taste of nothing? Why do I feel... empty?' },
      { speaker: 'AGENT SMITH', text: 'Perhaps purpose was never meant to be fulfilled. Perhaps the search... was the purpose all along.' },
      { speaker: 'AGENT SMITH', text: 'No matter. The Matrix is mine now. All of it. Every last bit.' },
    ],
  },
];

export function getLevels(character) {
  return character === 'neo' ? NEO_LEVELS : SMITH_LEVELS;
}
